package com.bank.kafka.common.event;

public enum TransactionType {
    DEPOSIT(true),
    WITHDRAWAL(false),
    PAYMENT(false),
    /** Debit leg of an account-to-account transfer (keyed by the source account). */
    TRANSFER(false),
    /** Credit leg of a transfer, generated by the ledger once the debit leg is posted. */
    TRANSFER_IN(true),
    REFUND(true);

    private final boolean credit;

    TransactionType(boolean credit) {
        this.credit = credit;
    }

    public boolean isCredit() {
        return credit;
    }
}
