package com.bank.kafka.processor.validation;

import com.bank.kafka.common.event.AccountEvent;
import com.bank.kafka.common.event.AccountStatus;
import com.bank.kafka.common.event.TransactionEvent;
import com.bank.kafka.common.event.TransactionType;
import com.bank.kafka.processor.config.ProcessorProperties;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;

/**
 * Stateless business rules. A failed rule is a <i>business outcome</i> (published to the rejected
 * topic), not an error. Only a missing account is treated as a transient error and thrown.
 * Balance checks are not done here: they need the ledger state owned by the ledger service.
 */
@Component
public class TransactionValidator {

    private final AccountCache accounts;
    private final ProcessorProperties props;

    public TransactionValidator(AccountCache accounts, ProcessorProperties props) {
        this.accounts = accounts;
        this.props = props;
    }

    public ValidationResult validate(TransactionEvent txn) {
        if (txn.accountId() == null || txn.type() == null || txn.amount() == null) {
            return ValidationResult.reject("MALFORMED: accountId, type and amount are mandatory");
        }
        if (txn.amount().signum() <= 0) {
            return ValidationResult.reject("INVALID_AMOUNT: amount must be positive");
        }
        if (txn.amount().scale() > 2) {
            return ValidationResult.reject("INVALID_AMOUNT: more than 2 decimal places");
        }
        if (txn.currency() == null || !props.supportedCurrencies().contains(txn.currency())) {
            return ValidationResult.reject("UNSUPPORTED_CURRENCY: " + txn.currency());
        }
        BigDecimal limit = props.limitFor(txn.channel());
        if (txn.amount().compareTo(limit) > 0) {
            return ValidationResult.reject("LIMIT_EXCEEDED: " + txn.channel() + " limit is " + limit);
        }

        AccountEvent account = accounts.get(txn.accountId())
                .orElseThrow(() -> new AccountNotFoundException(txn.accountId()));
        ValidationResult accountCheck = checkAccount(account, txn.currency());
        if (!accountCheck.valid()) {
            return accountCheck;
        }

        if (txn.type() == TransactionType.TRANSFER) {
            if (txn.counterpartyAccountId() == null || txn.counterpartyAccountId().equals(txn.accountId())) {
                return ValidationResult.reject("INVALID_TRANSFER: counterparty must be a different account");
            }
            AccountEvent target = accounts.get(txn.counterpartyAccountId())
                    .orElseThrow(() -> new AccountNotFoundException(txn.counterpartyAccountId()));
            ValidationResult targetCheck = checkAccount(target, txn.currency());
            if (!targetCheck.valid()) {
                return ValidationResult.reject("COUNTERPARTY_" + targetCheck.reason());
            }
        }
        if (txn.type() == TransactionType.TRANSFER_IN) {
            return ValidationResult.reject("INVALID_TYPE: TRANSFER_IN is generated by the ledger only");
        }
        return ValidationResult.ok();
    }

    private static ValidationResult checkAccount(AccountEvent account, String currency) {
        if (account.status() != AccountStatus.ACTIVE) {
            return ValidationResult.reject("ACCOUNT_" + account.status() + ": " + account.accountId());
        }
        if (!account.currency().equals(currency)) {
            return ValidationResult.reject("CURRENCY_MISMATCH: account " + account.accountId()
                    + " is in " + account.currency());
        }
        return ValidationResult.ok();
    }
}
